**NumPy ufuncs**


ufuncs stands for "Universal Functions" and they are NumPy functions that operate on the ndarray object.

ufuncs are used to implement vectorization in NumPy which is way faster than iterating over elements.



In [ ]:
#Without ufunc, we can use Python's built-in zip() method

x = [1,2,3,3]
y = [4,5,6,7]
for i,j in zip(x,y):

  print(i,j)

1 4
2 5
3 6
3 7


In [ ]:
# Without ufunc, we can use Python's built-in zip() method
x = [1,2,3,4]
y = [3,4,5,6]
z = []
for i,j in zip(x,y):
  z.append(i+j)
  print(z)

[4]
[4, 6]
[4, 6, 8]
[4, 6, 8, 10]


In [ ]:
import numpy as np
x = [1,2,35,6]
y = [9,8,7,6]
z = np.add(x,y)
print(z)

[10 10 42 12]


In [ ]:
import numpy as np
x = [1,2,3,4]
y = [3,4,5,6]
z = np.subtract(x,y)
print(z)


[-2 -2 -2 -2]


In [ ]:
import numpy as np
def myadd(x,y):
  return x+y
myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1, 2, 3, 4], [5, 6, 7, 8]))

[6 8 10 12]


In [ ]:
import numpy as np
print(type(np.add))

<class 'numpy.ufunc'>


In [ ]:
import numpy as np
x = np.array([9,8,6,2,4,5])
y = np.array([7,5,6,2,1,3])
print(np.add(x,y))


[16 13 12  4  5  8]


In [ ]:
import numpy as np
x = np.array([9,8,6,2,4,5])
y = np.array([7,5,6,2,1,3])
print(np.subtract(x,y))

[2 3 0 0 3 2]


In [ ]:
import numpy as np
x = np.array([9,8,6,2,4,5])
y = np.array([7,5,6,2,1,3])
print(np.multiply(x,y))

[63 40 36  4  4 15]


In [ ]:
import numpy as np
x = np.array([9,8,6,2,4,5])
y = np.array([7,5,6,2,1,3])
print(np.divide(x,y))

[1.28571429 1.6        1.         1.         4.         1.66666667]


In [ ]:
import numpy as np
x = np.array([9,8,6,2,4,5])
y = np.array([7,5,6,2,1,3])
print(np.power(x,y))
print(np.mod(x,y))
print(np.remainder(x,y))
print(np.absolute(x,y))

[4782969   32768   46656       4       4     125]
[2 3 0 0 0 2]
[2 3 0 0 0 2]
[9 8 6 2 4 5]


In [22]:
import numpy as np
arr = np.trunc([-3.1666, 3.6667])
print(arr)
arr = np.around([-3.1666, 3.6667])
print(arr)
arr  = np.floor([-3.1666, 3.6667])
print(arr)
arr = np.fix([-3.1666, 3.6667])
print(arr)
arr = np.ceil([-3.1666, 3.6667])
print(arr)

[-3.  3.]
[-3.  4.]
[-4.  3.]
[-3.  3.]
[-3.  4.]


In [25]:
import numpy as np
arr = np.arange(1,10)
print(np.log2(arr))


[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [26]:
import numpy as np
arr = np.arange(1,10)
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [28]:
import numpy as np
arr = np.arange(1,10)
print(np.log(arr))
#print(np.loge(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [29]:
import numpy as np
x = 10
y = 45
k = np.lcm(x,y)
print(k)

90


In [34]:
import numpy as np
x = 99
y = 66
k = np.lcm(x,y)
c = np.gcd(x,y)
print(k)
print(c)

198
33


In [32]:
import numpy as pa1
x = 88
y = 125
k = pa1.lcm(x,y)
print(k)

11000


In [35]:
import numpy as np
x = np.sin(np.pi/2)
print(x)

1.0


In [42]:
import numpy as np
x = np.array([np.pi/2,np.pi/3,np.pi/4])
print(np.sin(x))

[1.         0.8660254  0.70710678]


In [43]:
print(np.cos(x))

[6.12323400e-17 5.00000000e-01 7.07106781e-01]


In [44]:
print(np.tan(x))

[1.63312394e+16 1.73205081e+00 1.00000000e+00]


In [37]:
import numpy as np
x = np.sin([np.pi/2,np.pi/3,np.pi/4])
print(x)

[1.         0.8660254  0.70710678]


In [41]:
import numpy as np
x = np.cos([np.pi/2,np.pi/3,np.pi/4])
x1 = np.tan([np.pi/2,np.pi/3,np.pi/4])
x2 = np.sin([np.pi/2,np.pi/3,np.pi/4])
print(x2)
print(x)
print(x1)

[1.         0.8660254  0.70710678]
[6.12323400e-17 5.00000000e-01 7.07106781e-01]
[1.63312394e+16 1.73205081e+00 1.00000000e+00]


In [47]:
print(np.arcsin(x))

[       nan        nan 0.90333911]


/tmp/ipython-input-835714997.py:1: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))


In [55]:
print(np.arccos(x))
print(np.arctan(x))

nan
1.473050747060915


/tmp/ipython-input-814762016.py:1: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(x))


In [54]:
# NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.
import numpy as np
base = 2
perpend = 10
x = np.hypot(base,perpend)
print(x)


10.198039027185569


In [57]:
import numpy as np
x = np.array([np.pi/2,np.pi/3,np.pi/4])
print(np.sinh(x))

[2.3012989  1.24936705 0.86867096]


In [61]:
print(np.cosh(x))
print(np.tanh(x))
print(np.arctanh(x))
print(np.arcsin(x))


[2.50917848 1.60028686 1.32460909]
[0.91715234 0.78071444 0.6557942 ]
[       nan        nan 1.05930617]
[       nan        nan 0.90333911]


/tmp/ipython-input-1539168715.py:3: RuntimeWarning: invalid value encountered in arctanh
  print(np.arctanh(x))
/tmp/ipython-input-1539168715.py:4: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))


In [63]:
import numpy as np
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
x = np.unique(arr)
print(x)

[1 2 3 4 5 6 7]


In [65]:
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 5, 6])
v = np.union1d(x,y)
print(v)

[1 2 3 4 5 6]


In [66]:
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 5, 6])
v = np.intersect1d(x,y)
print(v)

[3 4]


In [67]:
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([3, 4, 5, 6])
v = np.setdiff1d(x,y)
print(v)

[1 2]
